In [14]:
# Decision Tree Classification

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print('Done Boss !!')

Done Boss !!


In [20]:
# Importing the dataset
dataset = pd.read_csv('ECG_NAGPUR-1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)
print('Done Boss !!')

[[0.40677966 0.4039548  0.40112994 ... 0.71186441 0.70338983 0.69774011]
 [0.71125265 0.70912951 0.71125265 ... 0.91932059 0.92569002 0.92569002]
 [0.43808256 0.43808256 0.43408788 ... 0.39147803 0.38881491 0.38881491]
 ...
 [0.48329049 0.4781491  0.47557841 ... 0.4781491  0.4781491  0.48071979]
 [0.22473868 0.22473868 0.21777004 ... 0.24390244 0.24216028 0.23170732]
 [0.72865275 0.73055028 0.73434535 ... 0.85009488 0.83301708 0.81783681]]
[1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0
 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0]
Done Boss !!


In [22]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)
print(X_test)
print(y_train)
print(y_test)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))
print('Done Boss !!')

[[0.64731183 0.6516129  0.65376344 ... 0.60645161 0.61075269 0.60430107]
 [0.7486911  0.7460733  0.73821989 ... 0.78272251 0.78795812 0.78795812]
 [0.6641791  0.65671642 0.64925373 ... 0.7761194  0.78109453 0.78606965]
 ...
 [0.99238579 0.96954315 0.90101523 ... 0.79441624 0.7893401  0.79187817]
 [0.5744186  0.5744186  0.58604651 ... 0.39534884 0.39767442 0.4       ]
 [0.78289474 0.77960526 0.77631579 ... 0.81907895 0.82894737 0.83552632]]
[[0.79207921 0.78877888 0.79867987 ... 0.74917492 0.74257426 0.73927393]
 [0.79207921 0.78877888 0.79867987 ... 0.74917492 0.74257426 0.73927393]
 [0.90723056 0.89358799 0.88130969 ... 0.62619372 0.62619372 0.62619372]
 ...
 [0.51311953 0.51311953 0.51020408 ... 0.52769679 0.51603499 0.51603499]
 [0.22473868 0.22473868 0.21777004 ... 0.24390244 0.24216028 0.23170732]
 [0.54545455 0.54545455 0.54882155 ... 0.59259259 0.58585859 0.57912458]]
[0 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 0 1 1 1 1 0 0 1 0 0 0 0
 1 0 1 0 1 0 1 1 0 0 1 1 1 0 0]
[0 1 

In [23]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)
print(len(X_train))
print(len(X_test))
print('Done Boss !!')

[[ 0.07972371  0.12732995  0.15638707 ... -0.2007831  -0.1804741
  -0.19881986]
 [ 0.67572202  0.67477959  0.64628965 ...  0.74488251  0.76921766
   0.78651041]
 [ 0.17888469  0.15690761  0.1302278  ...  0.70945786  0.73243384
   0.7763787 ]
 ...
 [ 2.10837803  1.96990957  1.59060888 ...  0.80761753  0.7766241
   0.80754174]
 [-0.34880805 -0.32005323 -0.23641534 ... -1.33331622 -1.32241812
  -1.29490653]
 [ 0.87680169  0.86911566  0.86727071 ...  0.93992904  0.98889015
   1.04171647]]
[[ 0.93079625  0.92228178  0.99699697 ...  0.56490494  0.5259933
   0.52531703]
 [ 0.93079625  0.92228178  0.99699697 ...  0.56490494  0.5259933
   0.52531703]
 [ 1.6077592   1.52970793  1.47630387 ... -0.09486978 -0.09772142
  -0.08136457]
 ...
 [-0.70917898 -0.67531486 -0.67635096 ... -0.62329029 -0.68809187
  -0.67237236]
 [-2.40454039 -2.34663963 -2.37265938 ... -2.14580228 -2.15586042
  -2.19780617]
 [-0.51908478 -0.48791579 -0.45234443 ... -0.27513455 -0.31388832
  -0.33389316]]
52
18
Done Boss !!


In [18]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
print('Done Boss !!')

Done Boss !!


In [19]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc = accuracy_score(y_test, y_pred)
print(acc)
print('Done Boss !!')

[[6 5]
 [0 7]]
0.7222222222222222
Done Boss !!
