In [1]:
import numpy as np
import pandas as pd
print('Done Boss !!')

Done Boss !!


In [2]:
import tensorflow as tf
print('Done Boss !!')

Done Boss !!


In [3]:
dataset = pd.read_csv('Lead-V2.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[0.24489796 0.23469388 0.2244898  ... 0.67346939 0.66326531 0.66326531]
 [0.66204506 0.66031196 0.65857886 ... 0.98613518 0.99306759 1.        ]
 [0.68195719 0.68195719 0.67584098 ... 0.65443425 0.65749236 0.65137615]
 ...
 [0.32129964 0.31046931 0.29602888 ... 0.28519856 0.29241877 0.31768953]
 [0.77142857 0.76507936 0.75238095 ... 0.93333333 0.93333333 0.93333333]
 [0.59685864 0.59685864 0.58813264 ... 0.59685864 0.60034904 0.59162304]]


In [5]:
print(y)

[1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 1
 0 1 0 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 1 1 1 1
 0 0 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1
 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 0 0 1 1 1 0 0 0 1 1
 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0
 0 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 0 1 0 1 1 0
 1 1 1 1 0 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 0
 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 1 1
 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 0 0
 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1
 1 0 1 0 1 0 1 0 1 0 1 1 

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print('Done Boss !!')

Done Boss !!


In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print('Done Boss !!')

Done Boss !!


In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size = 50, epochs = 100)

Epoch 1/100
9/9 [==============================] - 5s 311ms/step - loss: 8.8360 - accuracy: 0.5057
Epoch 2/100
9/9 [==============================] - 3s 298ms/step - loss: 5.3866 - accuracy: 0.5283
Epoch 3/100
9/9 [==============================] - 3s 296ms/step - loss: 1.3331 - accuracy: 0.6213
Epoch 4/100
9/9 [==============================] - 3s 295ms/step - loss: 0.7607 - accuracy: 0.6440
Epoch 5/100
9/9 [==============================] - 3s 296ms/step - loss: 0.6311 - accuracy: 0.7619
Epoch 6/100
9/9 [==============================] - 3s 296ms/step - loss: 0.8012 - accuracy: 0.7370
Epoch 7/100
9/9 [==============================] - 3s 307ms/step - loss: 0.7640 - accuracy: 0.7914
Epoch 8/100
9/9 [==============================] - 3s 332ms/step - loss: 0.6962 - accuracy: 0.7642
Epoch 9/100
9/9 [==============================] - 3s 345ms/step - loss: 0.4549 - accuracy: 0.8141
Epoch 10/100
9/9 [==============================] - 3s 340ms/step - loss: 0.3295 - accuracy: 0.9048
Epoch 11/

9/9 [==============================] - 3s 309ms/step - loss: 7.8542e-05 - accuracy: 1.0000
Epoch 83/100
9/9 [==============================] - 3s 307ms/step - loss: 7.1559e-05 - accuracy: 1.0000
Epoch 84/100
9/9 [==============================] - 3s 299ms/step - loss: 6.5328e-05 - accuracy: 1.0000
Epoch 85/100
9/9 [==============================] - 3s 305ms/step - loss: 6.0161e-05 - accuracy: 1.0000
Epoch 86/100
9/9 [==============================] - 3s 315ms/step - loss: 5.5536e-05 - accuracy: 1.0000
Epoch 87/100
9/9 [==============================] - 3s 302ms/step - loss: 5.1136e-05 - accuracy: 1.0000
Epoch 88/100
9/9 [==============================] - 3s 306ms/step - loss: 4.7319e-05 - accuracy: 1.0000
Epoch 89/100
9/9 [==============================] - 3s 301ms/step - loss: 4.3713e-05 - accuracy: 1.0000
Epoch 90/100
9/9 [==============================] - 3s 305ms/step - loss: 4.0624e-05 - accuracy: 1.0000
Epoch 91/100
9/9 [==============================] - 3s 303ms/step - loss: 3.7

In [14]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

5/5 [==============================] - 0s 32ms/step
[[1 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[17 29]
 [32 69]]


0.5850340136054422