In [1]:
import numpy as np
import pandas as pd
print('Done Boss !!')

Done Boss !!


In [2]:
import tensorflow as tf
print('Done Boss !!')

Done Boss !!


In [3]:
dataset = pd.read_csv('Lead-3.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values
print('Done Boss !!')

Done Boss !!


In [4]:
print(X)

[[0.22       0.22666667 0.22       ... 0.26666667 0.26       0.26666667]
 [0.28571429 0.27857143 0.26428571 ... 0.22857143 0.22857143 0.2       ]
 [0.11926605 0.1146789  0.09174312 ... 0.07798165 0.0733945  0.06880734]
 ...
 [0.48275862 0.42528736 0.31034483 ... 0.35632184 0.40229885 0.35632184]
 [0.24038461 0.23076923 0.25       ... 0.19230769 0.16346154 0.19230769]
 [0.68817204 0.66666667 0.65949821 ... 0.65591398 0.62007168 0.62365591]]


In [5]:
print(y)

[1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 1
 0 1 0 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 1 1 1 1
 0 0 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1
 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 0 0 1 1 1 0 0 0 1 1
 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0
 0 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 0 1 0 1 1 0
 1 1 1 1 0 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 0
 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 1 1
 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 0 0
 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1
 1 0 1 0 1 0 1 0 1 0 1 1 

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print('Done Boss !!')

Done Boss !!


In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print('Done Boss !!')

Done Boss !!


In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size = 50, epochs = 100)

Epoch 1/100
9/9 [==============================] - 5s 300ms/step - loss: 24.0894 - accuracy: 0.5669
Epoch 2/100
9/9 [==============================] - 3s 296ms/step - loss: 4.4418 - accuracy: 0.5578
Epoch 3/100
9/9 [==============================] - 3s 300ms/step - loss: 4.2340 - accuracy: 0.5760
Epoch 4/100
9/9 [==============================] - 3s 299ms/step - loss: 5.4563 - accuracy: 0.4649
Epoch 5/100
9/9 [==============================] - 3s 298ms/step - loss: 3.2962 - accuracy: 0.6508
Epoch 6/100
9/9 [==============================] - 3s 298ms/step - loss: 1.6527 - accuracy: 0.5283
Epoch 7/100
9/9 [==============================] - 3s 299ms/step - loss: 0.9638 - accuracy: 0.6281
Epoch 8/100
9/9 [==============================] - 3s 300ms/step - loss: 0.9278 - accuracy: 0.6485
Epoch 9/100
9/9 [==============================] - 3s 297ms/step - loss: 0.7135 - accuracy: 0.6848
Epoch 10/100
9/9 [==============================] - 3s 298ms/step - loss: 0.7230 - accuracy: 0.6825
Epoch 11

9/9 [==============================] - 3s 299ms/step - loss: 1.2413e-04 - accuracy: 1.0000
Epoch 82/100
9/9 [==============================] - 3s 299ms/step - loss: 1.1938e-04 - accuracy: 1.0000
Epoch 83/100
9/9 [==============================] - 3s 300ms/step - loss: 1.1554e-04 - accuracy: 1.0000
Epoch 84/100
9/9 [==============================] - 3s 298ms/step - loss: 1.1173e-04 - accuracy: 1.0000
Epoch 85/100
9/9 [==============================] - 3s 308ms/step - loss: 1.0704e-04 - accuracy: 1.0000
Epoch 86/100
9/9 [==============================] - 3s 303ms/step - loss: 1.0394e-04 - accuracy: 1.0000
Epoch 87/100
9/9 [==============================] - 3s 299ms/step - loss: 1.0012e-04 - accuracy: 1.0000
Epoch 88/100
9/9 [==============================] - 3s 299ms/step - loss: 9.7413e-05 - accuracy: 1.0000
Epoch 89/100
9/9 [==============================] - 3s 301ms/step - loss: 9.3819e-05 - accuracy: 1.0000
Epoch 90/100
9/9 [==============================] - 3s 296ms/step - loss: 9.0

In [15]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

5/5 [==============================] - 0s 31ms/step
[[0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[22 24]
 [31 70]]


0.6258503401360545