In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
dataset = pd.read_csv('ECG_NAGPUR-3.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[0.40677966 0.4039548  0.40112994 ... 0.71186441 0.70338983 0.69774011]
 [0.71125265 0.70912951 0.71125265 ... 0.91932059 0.92569002 0.92569002]
 [0.43808256 0.43808256 0.43408788 ... 0.39147803 0.38881491 0.38881491]
 ...
 [0.87704918 0.87704918 0.88934426 ... 0.73770492 0.73360656 0.74180328]
 [0.68804159 0.68284229 0.67764298 ... 0.86481802 0.86655113 0.86655113]
 [0.77031802 0.77031802 0.77031802 ... 0.67137809 0.66431095 0.67137809]]


In [5]:
print(y)

[1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0
 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1
 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 0 0
 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size = 50, epochs = 100)

Epoch 1/100
5/5 [==============================] - 4s 313ms/step - loss: 17.4649 - accuracy: 0.5250
Epoch 2/100
5/5 [==============================] - 1s 280ms/step - loss: 3.3283 - accuracy: 0.5542
Epoch 3/100
5/5 [==============================] - 1s 284ms/step - loss: 1.7682 - accuracy: 0.5750
Epoch 4/100
5/5 [==============================] - 1s 276ms/step - loss: 2.6716 - accuracy: 0.6167
Epoch 5/100
5/5 [==============================] - 1s 285ms/step - loss: 2.0960 - accuracy: 0.6708
Epoch 6/100
5/5 [==============================] - 1s 292ms/step - loss: 1.1689 - accuracy: 0.6500
Epoch 7/100
5/5 [==============================] - 1s 290ms/step - loss: 0.5581 - accuracy: 0.7583
Epoch 8/100
5/5 [==============================] - 1s 286ms/step - loss: 0.3559 - accuracy: 0.8625
Epoch 9/100
5/5 [==============================] - 1s 288ms/step - loss: 0.5999 - accuracy: 0.8333
Epoch 10/100
5/5 [==============================] - 1s 280ms/step - loss: 0.4468 - accuracy: 0.8083
Epoch 11

5/5 [==============================] - 1s 297ms/step - loss: 0.0131 - accuracy: 0.9917
Epoch 84/100
5/5 [==============================] - 2s 316ms/step - loss: 0.0134 - accuracy: 0.9917
Epoch 85/100
5/5 [==============================] - 2s 302ms/step - loss: 0.0124 - accuracy: 0.9917
Epoch 86/100
5/5 [==============================] - 2s 314ms/step - loss: 0.0124 - accuracy: 0.9875
Epoch 87/100
5/5 [==============================] - 2s 315ms/step - loss: 0.0128 - accuracy: 0.9917
Epoch 88/100
5/5 [==============================] - 2s 313ms/step - loss: 0.0126 - accuracy: 0.9875
Epoch 89/100
5/5 [==============================] - 2s 299ms/step - loss: 0.0131 - accuracy: 0.9875
Epoch 90/100
5/5 [==============================] - 1s 296ms/step - loss: 0.0126 - accuracy: 0.9875
Epoch 91/100
5/5 [==============================] - 2s 306ms/step - loss: 0.0122 - accuracy: 0.9917
Epoch 92/100
5/5 [==============================] - 1s 295ms/step - loss: 0.0140 - accuracy: 0.9917
Epoch 93/100


In [14]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

3/3 [==============================] - 0s 28ms/step
[[1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[12 17]
 [14 38]]


0.6172839506172839