In [1]:
import numpy as np
import pandas as pd
print('Done Boss !!')

Done Boss !!


In [2]:
import tensorflow as tf
print('Done Boss !!')

Done Boss !!


In [3]:
dataset = pd.read_csv('Lead-V3.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values
print('Done Boss !!')

Done Boss !!


In [4]:
print(X)

[[0.40677966 0.4039548  0.40112994 ... 0.71186441 0.70338983 0.69774011]
 [0.71125265 0.70912951 0.71125265 ... 0.91932059 0.92569002 0.92569002]
 [0.43808256 0.43808256 0.43408788 ... 0.39147803 0.38881491 0.38881491]
 ...
 [0.23033708 0.22752809 0.21629213 ... 0.1741573  0.18820225 0.21067416]
 [0.70438799 0.69745958 0.69053118 ... 0.89838337 0.89838337 0.90069284]
 [0.55495251 0.55223881 0.54545455 ... 0.54816825 0.55088195 0.54409769]]


In [5]:
print(y)

[1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 1
 0 1 0 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 1 1 1 1
 0 0 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1
 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 0 0 1 1 1 0 0 0 1 1
 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0
 0 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 0 1 0 1 1 0
 1 1 1 1 0 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 0
 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 1 1
 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 0 0
 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1
 1 0 1 0 1 0 1 0 1 0 1 1 

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print('Done Boss !!')

Done Boss !!


In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print('Done Boss !!')

Done Boss !!


In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size = 50, epochs = 100)

Epoch 1/100
9/9 [==============================] - 5s 297ms/step - loss: 10.6069 - accuracy: 0.4921
Epoch 2/100
9/9 [==============================] - 3s 300ms/step - loss: 2.7332 - accuracy: 0.5533
Epoch 3/100
9/9 [==============================] - 3s 297ms/step - loss: 1.8260 - accuracy: 0.5510
Epoch 4/100
9/9 [==============================] - 3s 299ms/step - loss: 1.0989 - accuracy: 0.6576
Epoch 5/100
9/9 [==============================] - 3s 307ms/step - loss: 0.6649 - accuracy: 0.7166
Epoch 6/100
9/9 [==============================] - 3s 299ms/step - loss: 0.4270 - accuracy: 0.8345
Epoch 7/100
9/9 [==============================] - 3s 302ms/step - loss: 0.3644 - accuracy: 0.8912
Epoch 8/100
9/9 [==============================] - 3s 299ms/step - loss: 0.3214 - accuracy: 0.9138
Epoch 9/100
9/9 [==============================] - 3s 298ms/step - loss: 0.2426 - accuracy: 0.9592
Epoch 10/100
9/9 [==============================] - 3s 301ms/step - loss: 0.2088 - accuracy: 0.9569
Epoch 11

9/9 [==============================] - 3s 307ms/step - loss: 2.2985e-05 - accuracy: 1.0000
Epoch 82/100
9/9 [==============================] - 3s 301ms/step - loss: 2.2123e-05 - accuracy: 1.0000
Epoch 83/100
9/9 [==============================] - 3s 304ms/step - loss: 2.1356e-05 - accuracy: 1.0000
Epoch 84/100
9/9 [==============================] - 3s 303ms/step - loss: 2.0607e-05 - accuracy: 1.0000
Epoch 85/100
9/9 [==============================] - 3s 300ms/step - loss: 1.9904e-05 - accuracy: 1.0000
Epoch 86/100
9/9 [==============================] - 3s 302ms/step - loss: 1.9214e-05 - accuracy: 1.0000
Epoch 87/100
9/9 [==============================] - 3s 305ms/step - loss: 1.8546e-05 - accuracy: 1.0000
Epoch 88/100
9/9 [==============================] - 3s 303ms/step - loss: 1.8035e-05 - accuracy: 1.0000
Epoch 89/100
9/9 [==============================] - 3s 301ms/step - loss: 1.7382e-05 - accuracy: 1.0000
Epoch 90/100
9/9 [==============================] - 3s 304ms/step - loss: 1.6

In [14]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

5/5 [==============================] - 0s 30ms/step
[[1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[12 34]
 [30 71]]


0.564625850340136