In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
dataset = pd.read_csv('ECG_NAGPUR-4.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[0.40677966 0.4039548  0.40112994 ... 0.71186441 0.70338983 0.69774011]
 [0.71125265 0.70912951 0.71125265 ... 0.91932059 0.92569002 0.92569002]
 [0.43808256 0.43808256 0.43408788 ... 0.39147803 0.38881491 0.38881491]
 ...
 [0.68804159 0.68284229 0.67764298 ... 0.86481802 0.86655113 0.86655113]
 [0.77031802 0.77031802 0.77031802 ... 0.67137809 0.66431095 0.67137809]
 [0.37179487 0.37948718 0.37435897 ... 0.39230769 0.38974359 0.3974359 ]]


In [5]:
print(y)

[1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0
 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1
 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 0 0
 1 1 1 0 1 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0
 1 1 1 1 0 1 1 1 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 0
 0 0 1 0 1 1 0 0 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 0 0
 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 1]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size = 50, epochs = 100)

Epoch 1/100
7/7 [==============================] - 4s 283ms/step - loss: 24.5379 - accuracy: 0.5617
Epoch 2/100
7/7 [==============================] - 2s 277ms/step - loss: 2.3447 - accuracy: 0.6358
Epoch 3/100
7/7 [==============================] - 2s 274ms/step - loss: 1.0715 - accuracy: 0.6698
Epoch 4/100
7/7 [==============================] - 2s 290ms/step - loss: 0.8297 - accuracy: 0.6605
Epoch 5/100
7/7 [==============================] - 2s 291ms/step - loss: 0.7081 - accuracy: 0.6821
Epoch 6/100
7/7 [==============================] - 2s 283ms/step - loss: 1.0095 - accuracy: 0.6574
Epoch 7/100
7/7 [==============================] - 2s 279ms/step - loss: 0.9197 - accuracy: 0.6975
Epoch 8/100
7/7 [==============================] - 2s 290ms/step - loss: 0.9761 - accuracy: 0.7037
Epoch 9/100
7/7 [==============================] - 2s 285ms/step - loss: 0.4511 - accuracy: 0.8117
Epoch 10/100
7/7 [==============================] - 2s 277ms/step - loss: 0.5307 - accuracy: 0.7901
Epoch 11

7/7 [==============================] - 2s 294ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 84/100
7/7 [==============================] - 2s 284ms/step - loss: 0.0085 - accuracy: 0.9969
Epoch 85/100
7/7 [==============================] - 2s 282ms/step - loss: 0.0088 - accuracy: 0.9969
Epoch 86/100
7/7 [==============================] - 2s 293ms/step - loss: 0.0048 - accuracy: 0.9969
Epoch 87/100
7/7 [==============================] - 2s 298ms/step - loss: 0.0054 - accuracy: 0.9969
Epoch 88/100
7/7 [==============================] - 2s 293ms/step - loss: 0.0061 - accuracy: 0.9969
Epoch 89/100
7/7 [==============================] - 2s 300ms/step - loss: 0.0063 - accuracy: 0.9969
Epoch 90/100
7/7 [==============================] - 2s 307ms/step - loss: 0.0056 - accuracy: 0.9938
Epoch 91/100
7/7 [==============================] - 2s 292ms/step - loss: 0.0051 - accuracy: 0.9969
Epoch 92/100
7/7 [==============================] - 2s 293ms/step - loss: 0.0054 - accuracy: 0.9938
Epoch 93/100


In [14]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

4/4 [==============================] - 0s 31ms/step
[[1 0]
 [0 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 7 16]
 [22 64]]


0.6513761467889908