In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
dataset = pd.read_csv('Lead-2.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[0.12758621 0.13103448 0.13793103 ... 0.25517241 0.25517241 0.25517241]
 [0.08680556 0.08333333 0.07986111 ... 0.21180556 0.21527778 0.21875   ]
 [0.08991826 0.09264305 0.08991826 ... 0.09809264 0.09264305 0.09809264]
 ...
 [0.34857143 0.32571429 0.30857143 ... 0.25714286 0.24571429 0.23428571]
 [0.18539326 0.20224719 0.16292135 ... 0.11797753 0.08988764 0.09550562]
 [0.18413598 0.17280453 0.17563739 ... 0.16997167 0.14164306 0.15580737]]


In [5]:
print(y)

[1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 1
 0 1 0 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 1 1 1 1
 0 0 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1
 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 0 0 1 1 1 0 0 0 1 1
 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0
 0 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 0 1 0 1 1 0
 1 1 1 1 0 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 0
 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 1 1
 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 0 0
 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1
 1 0 1 0 1 0 1 0 1 0 1 1 

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size = 50, epochs = 100)

Epoch 1/100
9/9 [==============================] - 5s 310ms/step - loss: 8.7063 - accuracy: 0.5828
Epoch 2/100
9/9 [==============================] - 3s 293ms/step - loss: 4.3882 - accuracy: 0.6077
Epoch 3/100
9/9 [==============================] - 3s 297ms/step - loss: 2.3665 - accuracy: 0.6871
Epoch 4/100
9/9 [==============================] - 3s 298ms/step - loss: 2.6687 - accuracy: 0.7937
Epoch 5/100
9/9 [==============================] - 3s 299ms/step - loss: 1.0561 - accuracy: 0.8073
Epoch 6/100
9/9 [==============================] - 3s 299ms/step - loss: 0.5027 - accuracy: 0.8776
Epoch 7/100
9/9 [==============================] - 3s 301ms/step - loss: 0.2768 - accuracy: 0.9070
Epoch 8/100
9/9 [==============================] - 3s 296ms/step - loss: 0.3069 - accuracy: 0.9048
Epoch 9/100
9/9 [==============================] - 3s 308ms/step - loss: 0.4134 - accuracy: 0.8821
Epoch 10/100
9/9 [==============================] - 3s 315ms/step - loss: 0.3047 - accuracy: 0.8912
Epoch 11/

9/9 [==============================] - 3s 299ms/step - loss: 1.1303e-04 - accuracy: 1.0000
Epoch 82/100
9/9 [==============================] - 3s 300ms/step - loss: 1.0979e-04 - accuracy: 1.0000
Epoch 83/100
9/9 [==============================] - 3s 298ms/step - loss: 1.0693e-04 - accuracy: 1.0000
Epoch 84/100
9/9 [==============================] - 3s 301ms/step - loss: 1.0390e-04 - accuracy: 1.0000
Epoch 85/100
9/9 [==============================] - 3s 307ms/step - loss: 1.0115e-04 - accuracy: 1.0000
Epoch 86/100
9/9 [==============================] - 3s 303ms/step - loss: 9.8524e-05 - accuracy: 1.0000
Epoch 87/100
9/9 [==============================] - 3s 300ms/step - loss: 9.5896e-05 - accuracy: 1.0000
Epoch 88/100
9/9 [==============================] - 3s 299ms/step - loss: 9.3602e-05 - accuracy: 1.0000
Epoch 89/100
9/9 [==============================] - 3s 301ms/step - loss: 9.1158e-05 - accuracy: 1.0000
Epoch 90/100
9/9 [==============================] - 3s 300ms/step - loss: 8.8

In [14]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

5/5 [==============================] - 0s 45ms/step
[[0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13 33]
 [34 67]]


0.54421768707483