In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
dataset = pd.read_csv('ECG_NAGPUR-5.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[0.40677966 0.4039548  0.40112994 ... 0.71186441 0.70338983 0.69774011]
 [0.71125265 0.70912951 0.71125265 ... 0.91932059 0.92569002 0.92569002]
 [0.43808256 0.43808256 0.43408788 ... 0.39147803 0.38881491 0.38881491]
 ...
 [0.23033708 0.22752809 0.21629213 ... 0.1741573  0.18820225 0.21067416]
 [0.70438799 0.69745958 0.69053118 ... 0.89838337 0.89838337 0.90069284]
 [0.55495251 0.55223881 0.54545455 ... 0.54816825 0.55088195 0.54409769]]


In [5]:
print(y)

[1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0
 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1
 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 0 0
 1 1 1 0 1 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0
 1 1 1 1 0 1 1 1 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 0
 0 0 1 0 1 1 0 0 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 0 0
 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0
 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0
 1 0 0 0 1 0 0 0 1 1 1 1 

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size = 50, epochs = 100)

Epoch 1/100
10/10 [==============================] - 6s 327ms/step - loss: 16.1714 - accuracy: 0.6209
Epoch 2/100
10/10 [==============================] - 3s 311ms/step - loss: 2.9039 - accuracy: 0.5795
Epoch 3/100
10/10 [==============================] - 3s 311ms/step - loss: 1.3071 - accuracy: 0.6209
Epoch 4/100
10/10 [==============================] - 3s 347ms/step - loss: 1.7948 - accuracy: 0.6275
Epoch 5/100
10/10 [==============================] - 3s 319ms/step - loss: 0.7565 - accuracy: 0.7495
Epoch 6/100
10/10 [==============================] - 3s 310ms/step - loss: 0.6729 - accuracy: 0.7516
Epoch 7/100
10/10 [==============================] - 3s 314ms/step - loss: 1.3547 - accuracy: 0.7146
Epoch 8/100
10/10 [==============================] - 3s 315ms/step - loss: 0.7788 - accuracy: 0.7516
Epoch 9/100
10/10 [==============================] - 3s 318ms/step - loss: 0.4984 - accuracy: 0.7778
Epoch 10/100
10/10 [==============================] - 3s 313ms/step - loss: 0.4356 - accur

10/10 [==============================] - 3s 347ms/step - loss: 0.0096 - accuracy: 0.9956
Epoch 82/100
10/10 [==============================] - 4s 349ms/step - loss: 0.0131 - accuracy: 0.9913
Epoch 83/100
10/10 [==============================] - 3s 348ms/step - loss: 0.0077 - accuracy: 0.9956
Epoch 84/100
10/10 [==============================] - 3s 336ms/step - loss: 0.0089 - accuracy: 0.9935
Epoch 85/100
10/10 [==============================] - 3s 341ms/step - loss: 0.0097 - accuracy: 0.9956
Epoch 86/100
10/10 [==============================] - 3s 344ms/step - loss: 0.0091 - accuracy: 0.9956
Epoch 87/100
10/10 [==============================] - 3s 337ms/step - loss: 0.0076 - accuracy: 0.9935
Epoch 88/100
10/10 [==============================] - 3s 341ms/step - loss: 0.0103 - accuracy: 0.9935
Epoch 89/100
10/10 [==============================] - 3s 344ms/step - loss: 0.0119 - accuracy: 0.9956
Epoch 90/100
10/10 [==============================] - 3s 339ms/step - loss: 0.0362 - accuracy: 

In [14]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

5/5 [==============================] - 0s 39ms/step
[[1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[10 32]
 [26 85]]


0.6209150326797386