In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
dataset = pd.read_csv('Lead-1.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[0.19512195 0.19512195 0.20731707 ... 0.32113821 0.32520325 0.31707317]
 [0.09543569 0.09543569 0.09958506 ... 0.28215768 0.28630705 0.30290456]
 [0.14795918 0.15816326 0.17857143 ... 0.20918367 0.20918367 0.21938775]
 ...
 [0.44571429 0.45142857 0.49142857 ... 0.42285714 0.38857143 0.39428571]
 [0.38926174 0.41610738 0.3557047  ... 0.34228188 0.32885906 0.31543624]
 [0.11049724 0.1160221  0.12430939 ... 0.12430939 0.12430939 0.13259668]]


In [5]:
print(y)

[1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 1
 0 1 0 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 1 1 1 1
 0 0 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1
 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 0 0 1 1 1 0 0 0 1 1
 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0
 0 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 0 1 0 1 1 0
 1 1 1 1 0 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 0
 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 1 1
 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 0 0
 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1
 1 0 1 0 1 0 1 0 1 0 1 1 

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=3700, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size = 50, epochs = 100)

Epoch 1/100
9/9 [==============================] - 4s 292ms/step - loss: 9.3747 - accuracy: 0.5397
Epoch 2/100
9/9 [==============================] - 3s 288ms/step - loss: 4.1191 - accuracy: 0.6032
Epoch 3/100
9/9 [==============================] - 3s 289ms/step - loss: 0.8074 - accuracy: 0.6916
Epoch 4/100
9/9 [==============================] - 3s 288ms/step - loss: 0.5162 - accuracy: 0.7687
Epoch 5/100
9/9 [==============================] - 3s 289ms/step - loss: 0.4241 - accuracy: 0.8163
Epoch 6/100
9/9 [==============================] - 3s 297ms/step - loss: 0.4713 - accuracy: 0.8254
Epoch 7/100
9/9 [==============================] - 3s 301ms/step - loss: 0.7075 - accuracy: 0.7800
Epoch 8/100
9/9 [==============================] - 3s 321ms/step - loss: 0.4680 - accuracy: 0.8435
Epoch 9/100
9/9 [==============================] - 3s 320ms/step - loss: 0.2657 - accuracy: 0.9070
Epoch 10/100
9/9 [==============================] - 3s 342ms/step - loss: 0.2131 - accuracy: 0.9161
Epoch 11/

9/9 [==============================] - 3s 304ms/step - loss: 2.2942e-05 - accuracy: 1.0000
Epoch 81/100
9/9 [==============================] - 3s 317ms/step - loss: 2.2106e-05 - accuracy: 1.0000
Epoch 82/100
9/9 [==============================] - 3s 314ms/step - loss: 2.1477e-05 - accuracy: 1.0000
Epoch 83/100
9/9 [==============================] - 3s 317ms/step - loss: 2.0642e-05 - accuracy: 1.0000
Epoch 84/100
9/9 [==============================] - 3s 330ms/step - loss: 1.9981e-05 - accuracy: 1.0000
Epoch 85/100
9/9 [==============================] - 3s 320ms/step - loss: 1.9335e-05 - accuracy: 1.0000
Epoch 86/100
9/9 [==============================] - 3s 317ms/step - loss: 1.8726e-05 - accuracy: 1.0000
Epoch 87/100
9/9 [==============================] - 3s 313ms/step - loss: 1.8135e-05 - accuracy: 1.0000
Epoch 88/100
9/9 [==============================] - 3s 323ms/step - loss: 1.7569e-05 - accuracy: 1.0000
Epoch 89/100
9/9 [==============================] - 3s 343ms/step - loss: 1.7

In [14]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

5/5 [==============================] - 0s 33ms/step
[[0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 7 39]
 [27 74]]


0.5510204081632653